var PATH_PLUGINS_PREFIX = './plugins/'
    , KEY_STORAGE_SETTINGS = "settings"
    , KEY_STORAGE_VIDEO_WIDTH = "videoWidthSetting"
    , KEY_STORAGE_VIDEO_HEIGHT = "videoHeightSetting"
    , KEY_STORAGE_ASPECT_RATIO = "aspectRatioSetting"
    , DEFAULT_AUTO_DOWNLOAD = false
    , DEFAULT_PICTURE_FORMAT = "png"
    , DEFAULT_VIDEO_WIDTH = 1080
    , DEFAULT_VIDEO_HEIGHT = 1080
    , DEFAULT_VIDEO_FRAME_RATE = 120
    , DEFAULT_VIDEO_QUALITY = 0.75
    , DEFAULT_ASPECT_RATIO = false
;
